# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blacksmith.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import item_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='blacksmith.proto',
  package='SanProto',
  serialized_pb=_b('\n\x10\x62lacksmith.proto\x12\x08SanProto\x1a\nitem.proto\"x\n\nCastingReq\x12\x0f\n\x07user_id\x18\x01 \x02(\x04\x12\x16\n\x0etarget_item_id\x18\x02 \x02(\x05\x12(\n\x0corigin_items\x18\x03 \x03(\x0b\x32\x12.SanProto.ItemInfo\x12\x17\n\x0ftarget_item_num\x18\x04 \x01(\x05\"E\n\nCastingRes\x12\x0e\n\x06status\x18\x01 \x02(\x05\x12\'\n\x0btarget_item\x18\x02 \x01(\x0b\x32\x12.SanProto.ItemInfo')
  ,
  dependencies=[item_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CASTINGREQ = _descriptor.Descriptor(
  name='CastingReq',
  full_name='SanProto.CastingReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='SanProto.CastingReq.user_id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_item_id', full_name='SanProto.CastingReq.target_item_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='origin_items', full_name='SanProto.CastingReq.origin_items', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_item_num', full_name='SanProto.CastingReq.target_item_num', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=162,
)


_CASTINGRES = _descriptor.Descriptor(
  name='CastingRes',
  full_name='SanProto.CastingRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='SanProto.CastingRes.status', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_item', full_name='SanProto.CastingRes.target_item', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=233,
)

_CASTINGREQ.fields_by_name['origin_items'].message_type = item_pb2._ITEMINFO
_CASTINGRES.fields_by_name['target_item'].message_type = item_pb2._ITEMINFO
DESCRIPTOR.message_types_by_name['CastingReq'] = _CASTINGREQ
DESCRIPTOR.message_types_by_name['CastingRes'] = _CASTINGRES

CastingReq = _reflection.GeneratedProtocolMessageType('CastingReq', (_message.Message,), dict(
  DESCRIPTOR = _CASTINGREQ,
  __module__ = 'blacksmith_pb2'
  # @@protoc_insertion_point(class_scope:SanProto.CastingReq)
  ))
_sym_db.RegisterMessage(CastingReq)

CastingRes = _reflection.GeneratedProtocolMessageType('CastingRes', (_message.Message,), dict(
  DESCRIPTOR = _CASTINGRES,
  __module__ = 'blacksmith_pb2'
  # @@protoc_insertion_point(class_scope:SanProto.CastingRes)
  ))
_sym_db.RegisterMessage(CastingRes)


# @@protoc_insertion_point(module_scope)
