# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: broadcast.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import tips_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='broadcast.proto',
  package='SanProto',
  serialized_pb=_b('\n\x0f\x62roadcast.proto\x12\x08SanProto\x1a\ntips.proto\"a\n\rBroadcastInfo\x12\x0f\n\x07mode_id\x18\x01 \x02(\x05\x12\x13\n\x0bpassed_time\x18\x02 \x02(\x05\x12\x0f\n\x07\x63ontent\x18\x03 \x02(\x0c\x12\n\n\x02id\x18\x04 \x01(\x05\x12\r\n\x05speed\x18\x05 \x01(\x05\"\x17\n\x15QueryBroadcastInfoReq\"\xa2\x01\n\x15QueryBroadcastInfoRes\x12\x0e\n\x06status\x18\x01 \x02(\x05\x12(\n\x07records\x18\x02 \x03(\x0b\x32\x17.SanProto.BroadcastInfo\x12)\n\x0b\x62utton_tips\x18\x03 \x03(\x0b\x32\x14.SanProto.ButtonTips\x12\x16\n\x0e\x63hat_available\x18\x04 \x01(\x08\x12\x0c\n\x04\x63hat\x18\x05 \x01(\x05\"m\n\x13\x41\x64\x64\x42roadcastInfoReq\x12\x0f\n\x07user_id\x18\x01 \x02(\x04\x12\x0f\n\x07mode_id\x18\x02 \x02(\x05\x12\x10\n\x08priority\x18\x03 \x02(\x05\x12\x11\n\tlife_time\x18\x04 \x02(\x05\x12\x0f\n\x07\x63ontent\x18\x05 \x02(\x0c\"%\n\x13\x41\x64\x64\x42roadcastInfoRes\x12\x0e\n\x06status\x18\x01 \x02(\x05\"%\n\x16\x44\x65leteBroadcastInfoReq\x12\x0b\n\x03ids\x18\x01 \x03(\x05\"(\n\x16\x44\x65leteBroadcastInfoRes\x12\x0e\n\x06status\x18\x01 \x02(\x05')
  ,
  dependencies=[tips_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BROADCASTINFO = _descriptor.Descriptor(
  name='BroadcastInfo',
  full_name='SanProto.BroadcastInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode_id', full_name='SanProto.BroadcastInfo.mode_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='passed_time', full_name='SanProto.BroadcastInfo.passed_time', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='SanProto.BroadcastInfo.content', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='SanProto.BroadcastInfo.id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='SanProto.BroadcastInfo.speed', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=138,
)


_QUERYBROADCASTINFOREQ = _descriptor.Descriptor(
  name='QueryBroadcastInfoReq',
  full_name='SanProto.QueryBroadcastInfoReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=163,
)


_QUERYBROADCASTINFORES = _descriptor.Descriptor(
  name='QueryBroadcastInfoRes',
  full_name='SanProto.QueryBroadcastInfoRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='SanProto.QueryBroadcastInfoRes.status', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='records', full_name='SanProto.QueryBroadcastInfoRes.records', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='button_tips', full_name='SanProto.QueryBroadcastInfoRes.button_tips', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chat_available', full_name='SanProto.QueryBroadcastInfoRes.chat_available', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chat', full_name='SanProto.QueryBroadcastInfoRes.chat', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=328,
)


_ADDBROADCASTINFOREQ = _descriptor.Descriptor(
  name='AddBroadcastInfoReq',
  full_name='SanProto.AddBroadcastInfoReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='SanProto.AddBroadcastInfoReq.user_id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mode_id', full_name='SanProto.AddBroadcastInfoReq.mode_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='priority', full_name='SanProto.AddBroadcastInfoReq.priority', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='life_time', full_name='SanProto.AddBroadcastInfoReq.life_time', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='SanProto.AddBroadcastInfoReq.content', index=4,
      number=5, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=439,
)


_ADDBROADCASTINFORES = _descriptor.Descriptor(
  name='AddBroadcastInfoRes',
  full_name='SanProto.AddBroadcastInfoRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='SanProto.AddBroadcastInfoRes.status', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=441,
  serialized_end=478,
)


_DELETEBROADCASTINFOREQ = _descriptor.Descriptor(
  name='DeleteBroadcastInfoReq',
  full_name='SanProto.DeleteBroadcastInfoReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='SanProto.DeleteBroadcastInfoReq.ids', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=480,
  serialized_end=517,
)


_DELETEBROADCASTINFORES = _descriptor.Descriptor(
  name='DeleteBroadcastInfoRes',
  full_name='SanProto.DeleteBroadcastInfoRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='SanProto.DeleteBroadcastInfoRes.status', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=519,
  serialized_end=559,
)

_QUERYBROADCASTINFORES.fields_by_name['records'].message_type = _BROADCASTINFO
_QUERYBROADCASTINFORES.fields_by_name['button_tips'].message_type = tips_pb2._BUTTONTIPS
DESCRIPTOR.message_types_by_name['BroadcastInfo'] = _BROADCASTINFO
DESCRIPTOR.message_types_by_name['QueryBroadcastInfoReq'] = _QUERYBROADCASTINFOREQ
DESCRIPTOR.message_types_by_name['QueryBroadcastInfoRes'] = _QUERYBROADCASTINFORES
DESCRIPTOR.message_types_by_name['AddBroadcastInfoReq'] = _ADDBROADCASTINFOREQ
DESCRIPTOR.message_types_by_name['AddBroadcastInfoRes'] = _ADDBROADCASTINFORES
DESCRIPTOR.message_types_by_name['DeleteBroadcastInfoReq'] = _DELETEBROADCASTINFOREQ
DESCRIPTOR.message_types_by_name['DeleteBroadcastInfoRes'] = _DELETEBROADCASTINFORES

BroadcastInfo = _reflection.GeneratedProtocolMessageType('BroadcastInfo', (_message.Message,), dict(
  DESCRIPTOR = _BROADCASTINFO,
  __module__ = 'broadcast_pb2'
  # @@protoc_insertion_point(class_scope:SanProto.BroadcastInfo)
  ))
_sym_db.RegisterMessage(BroadcastInfo)

QueryBroadcastInfoReq = _reflection.GeneratedProtocolMessageType('QueryBroadcastInfoReq', (_message.Message,), dict(
  DESCRIPTOR = _QUERYBROADCASTINFOREQ,
  __module__ = 'broadcast_pb2'
  # @@protoc_insertion_point(class_scope:SanProto.QueryBroadcastInfoReq)
  ))
_sym_db.RegisterMessage(QueryBroadcastInfoReq)

QueryBroadcastInfoRes = _reflection.GeneratedProtocolMessageType('QueryBroadcastInfoRes', (_message.Message,), dict(
  DESCRIPTOR = _QUERYBROADCASTINFORES,
  __module__ = 'broadcast_pb2'
  # @@protoc_insertion_point(class_scope:SanProto.QueryBroadcastInfoRes)
  ))
_sym_db.RegisterMessage(QueryBroadcastInfoRes)

AddBroadcastInfoReq = _reflection.GeneratedProtocolMessageType('AddBroadcastInfoReq', (_message.Message,), dict(
  DESCRIPTOR = _ADDBROADCASTINFOREQ,
  __module__ = 'broadcast_pb2'
  # @@protoc_insertion_point(class_scope:SanProto.AddBroadcastInfoReq)
  ))
_sym_db.RegisterMessage(AddBroadcastInfoReq)

AddBroadcastInfoRes = _reflection.GeneratedProtocolMessageType('AddBroadcastInfoRes', (_message.Message,), dict(
  DESCRIPTOR = _ADDBROADCASTINFORES,
  __module__ = 'broadcast_pb2'
  # @@protoc_insertion_point(class_scope:SanProto.AddBroadcastInfoRes)
  ))
_sym_db.RegisterMessage(AddBroadcastInfoRes)

DeleteBroadcastInfoReq = _reflection.GeneratedProtocolMessageType('DeleteBroadcastInfoReq', (_message.Message,), dict(
  DESCRIPTOR = _DELETEBROADCASTINFOREQ,
  __module__ = 'broadcast_pb2'
  # @@protoc_insertion_point(class_scope:SanProto.DeleteBroadcastInfoReq)
  ))
_sym_db.RegisterMessage(DeleteBroadcastInfoReq)

DeleteBroadcastInfoRes = _reflection.GeneratedProtocolMessageType('DeleteBroadcastInfoRes', (_message.Message,), dict(
  DESCRIPTOR = _DELETEBROADCASTINFORES,
  __module__ = 'broadcast_pb2'
  # @@protoc_insertion_point(class_scope:SanProto.DeleteBroadcastInfoRes)
  ))
_sym_db.RegisterMessage(DeleteBroadcastInfoRes)


# @@protoc_insertion_point(module_scope)
