# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: energy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import resource_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='energy.proto',
  package='SanProto',
  serialized_pb=_b('\n\x0c\x65nergy.proto\x12\x08SanProto\x1a\x0eresource.proto\"\x90\x01\n\nEnergyInfo\x12\x16\n\x0e\x63urrent_energy\x18\x01 \x01(\x05\x12\x13\n\x0bpassed_time\x18\x02 \x01(\x05\x12\x13\n\x0b\x65vent_types\x18\x03 \x03(\x05\x12\x15\n\revent_indexes\x18\x04 \x03(\x05\x12\x0f\n\x07\x62uy_num\x18\x05 \x01(\x05\x12\x18\n\x10next_refresh_gap\x18\x06 \x01(\x05\"\x1f\n\x0c\x42uyEnergyReq\x12\x0f\n\x07\x62uy_num\x18\x01 \x01(\x05\"s\n\x0c\x42uyEnergyRes\x12\x0e\n\x06status\x18\x01 \x02(\x05\x12)\n\x0b\x65nergy_info\x18\x02 \x01(\x0b\x32\x14.SanProto.EnergyInfo\x12(\n\x08resource\x18\x03 \x01(\x0b\x32\x16.SanProto.ResourceInfo\"\x16\n\x14RefreshEnergyInfoReq\"Q\n\x14RefreshEnergyInfoRes\x12\x0e\n\x06status\x18\x01 \x02(\x05\x12)\n\x0b\x65nergy_info\x18\x02 \x01(\x0b\x32\x14.SanProto.EnergyInfo')
  ,
  dependencies=[resource_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ENERGYINFO = _descriptor.Descriptor(
  name='EnergyInfo',
  full_name='SanProto.EnergyInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_energy', full_name='SanProto.EnergyInfo.current_energy', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='passed_time', full_name='SanProto.EnergyInfo.passed_time', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='event_types', full_name='SanProto.EnergyInfo.event_types', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='event_indexes', full_name='SanProto.EnergyInfo.event_indexes', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='buy_num', full_name='SanProto.EnergyInfo.buy_num', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='next_refresh_gap', full_name='SanProto.EnergyInfo.next_refresh_gap', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=187,
)


_BUYENERGYREQ = _descriptor.Descriptor(
  name='BuyEnergyReq',
  full_name='SanProto.BuyEnergyReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='buy_num', full_name='SanProto.BuyEnergyReq.buy_num', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=220,
)


_BUYENERGYRES = _descriptor.Descriptor(
  name='BuyEnergyRes',
  full_name='SanProto.BuyEnergyRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='SanProto.BuyEnergyRes.status', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='energy_info', full_name='SanProto.BuyEnergyRes.energy_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resource', full_name='SanProto.BuyEnergyRes.resource', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=337,
)


_REFRESHENERGYINFOREQ = _descriptor.Descriptor(
  name='RefreshEnergyInfoReq',
  full_name='SanProto.RefreshEnergyInfoReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=361,
)


_REFRESHENERGYINFORES = _descriptor.Descriptor(
  name='RefreshEnergyInfoRes',
  full_name='SanProto.RefreshEnergyInfoRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='SanProto.RefreshEnergyInfoRes.status', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='energy_info', full_name='SanProto.RefreshEnergyInfoRes.energy_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=363,
  serialized_end=444,
)

_BUYENERGYRES.fields_by_name['energy_info'].message_type = _ENERGYINFO
_BUYENERGYRES.fields_by_name['resource'].message_type = resource_pb2._RESOURCEINFO
_REFRESHENERGYINFORES.fields_by_name['energy_info'].message_type = _ENERGYINFO
DESCRIPTOR.message_types_by_name['EnergyInfo'] = _ENERGYINFO
DESCRIPTOR.message_types_by_name['BuyEnergyReq'] = _BUYENERGYREQ
DESCRIPTOR.message_types_by_name['BuyEnergyRes'] = _BUYENERGYRES
DESCRIPTOR.message_types_by_name['RefreshEnergyInfoReq'] = _REFRESHENERGYINFOREQ
DESCRIPTOR.message_types_by_name['RefreshEnergyInfoRes'] = _REFRESHENERGYINFORES

EnergyInfo = _reflection.GeneratedProtocolMessageType('EnergyInfo', (_message.Message,), dict(
  DESCRIPTOR = _ENERGYINFO,
  __module__ = 'energy_pb2'
  # @@protoc_insertion_point(class_scope:SanProto.EnergyInfo)
  ))
_sym_db.RegisterMessage(EnergyInfo)

BuyEnergyReq = _reflection.GeneratedProtocolMessageType('BuyEnergyReq', (_message.Message,), dict(
  DESCRIPTOR = _BUYENERGYREQ,
  __module__ = 'energy_pb2'
  # @@protoc_insertion_point(class_scope:SanProto.BuyEnergyReq)
  ))
_sym_db.RegisterMessage(BuyEnergyReq)

BuyEnergyRes = _reflection.GeneratedProtocolMessageType('BuyEnergyRes', (_message.Message,), dict(
  DESCRIPTOR = _BUYENERGYRES,
  __module__ = 'energy_pb2'
  # @@protoc_insertion_point(class_scope:SanProto.BuyEnergyRes)
  ))
_sym_db.RegisterMessage(BuyEnergyRes)

RefreshEnergyInfoReq = _reflection.GeneratedProtocolMessageType('RefreshEnergyInfoReq', (_message.Message,), dict(
  DESCRIPTOR = _REFRESHENERGYINFOREQ,
  __module__ = 'energy_pb2'
  # @@protoc_insertion_point(class_scope:SanProto.RefreshEnergyInfoReq)
  ))
_sym_db.RegisterMessage(RefreshEnergyInfoReq)

RefreshEnergyInfoRes = _reflection.GeneratedProtocolMessageType('RefreshEnergyInfoRes', (_message.Message,), dict(
  DESCRIPTOR = _REFRESHENERGYINFORES,
  __module__ = 'energy_pb2'
  # @@protoc_insertion_point(class_scope:SanProto.RefreshEnergyInfoRes)
  ))
_sym_db.RegisterMessage(RefreshEnergyInfoRes)


# @@protoc_insertion_point(module_scope)
