# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monarch.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import resource_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='monarch.proto',
  package='SanProto',
  serialized_pb=_b('\n\rmonarch.proto\x12\x08SanProto\x1a\x0eresource.proto\"\x81\x02\n\x0bMonarchInfo\x12\x0f\n\x07user_id\x18\x01 \x02(\x04\x12\x0c\n\x04name\x18\x02 \x01(\x0c\x12\r\n\x05level\x18\x03 \x01(\x05\x12\x0b\n\x03\x65xp\x18\x04 \x01(\x05\x12\x13\n\x0bheadicon_id\x18\x05 \x01(\x05\x12\x11\n\tvip_level\x18\x06 \x01(\x05\x12\x10\n\x08union_id\x18\x07 \x01(\x05\x12\x12\n\nvip_points\x18\x08 \x01(\x05\x12\x13\n\x0b\x63reate_time\x18\t \x01(\x05\x12\x13\n\x0binvite_code\x18\n \x01(\x0c\x12\x0f\n\x07inviter\x18\x0b \x01(\x04\x12\x0f\n\x07\x63ountry\x18\x0c \x01(\x05\x12\x0c\n\x04\x63oin\x18\r \x01(\x05\x12\x0f\n\x07payment\x18\x0e \x01(\x05\"M\n\x10UpdateMonarchReq\x12&\n\x07monarch\x18\x01 \x02(\x0b\x32\x15.SanProto.MonarchInfo\x12\x11\n\tgold_cost\x18\x02 \x01(\x05\"\"\n\x10UpdateMonarchRes\x12\x0e\n\x06status\x18\x01 \x02(\x05\"\x1a\n\x18QuerySuggestedCountryReq\"P\n\x18QuerySuggestedCountryRes\x12\x0e\n\x06status\x18\x01 \x02(\x05\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\x05\x12\x13\n\x0breward_gold\x18\x03 \x01(\x05\"z\n\x10UpdateCountryReq\x12\x13\n\x0bold_country\x18\x01 \x01(\x05\x12\x13\n\x0bnew_country\x18\x02 \x01(\x05\x12\x15\n\ritem_basic_id\x18\x03 \x01(\x05\x12\x10\n\x08item_num\x18\x04 \x01(\x05\x12\x13\n\x0breward_gold\x18\x05 \x01(\x05\"L\n\x10UpdateCountryRes\x12\x0e\n\x06status\x18\x01 \x02(\x05\x12(\n\x08resource\x18\x02 \x01(\x0b\x32\x16.SanProto.ResourceInfo')
  ,
  dependencies=[resource_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MONARCHINFO = _descriptor.Descriptor(
  name='MonarchInfo',
  full_name='SanProto.MonarchInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='SanProto.MonarchInfo.user_id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='SanProto.MonarchInfo.name', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='SanProto.MonarchInfo.level', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exp', full_name='SanProto.MonarchInfo.exp', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='headicon_id', full_name='SanProto.MonarchInfo.headicon_id', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vip_level', full_name='SanProto.MonarchInfo.vip_level', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='union_id', full_name='SanProto.MonarchInfo.union_id', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vip_points', full_name='SanProto.MonarchInfo.vip_points', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='create_time', full_name='SanProto.MonarchInfo.create_time', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='invite_code', full_name='SanProto.MonarchInfo.invite_code', index=9,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inviter', full_name='SanProto.MonarchInfo.inviter', index=10,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='country', full_name='SanProto.MonarchInfo.country', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coin', full_name='SanProto.MonarchInfo.coin', index=12,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payment', full_name='SanProto.MonarchInfo.payment', index=13,
      number=14, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=301,
)


_UPDATEMONARCHREQ = _descriptor.Descriptor(
  name='UpdateMonarchReq',
  full_name='SanProto.UpdateMonarchReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='monarch', full_name='SanProto.UpdateMonarchReq.monarch', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gold_cost', full_name='SanProto.UpdateMonarchReq.gold_cost', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=380,
)


_UPDATEMONARCHRES = _descriptor.Descriptor(
  name='UpdateMonarchRes',
  full_name='SanProto.UpdateMonarchRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='SanProto.UpdateMonarchRes.status', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=382,
  serialized_end=416,
)


_QUERYSUGGESTEDCOUNTRYREQ = _descriptor.Descriptor(
  name='QuerySuggestedCountryReq',
  full_name='SanProto.QuerySuggestedCountryReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=444,
)


_QUERYSUGGESTEDCOUNTRYRES = _descriptor.Descriptor(
  name='QuerySuggestedCountryRes',
  full_name='SanProto.QuerySuggestedCountryRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='SanProto.QuerySuggestedCountryRes.status', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='country', full_name='SanProto.QuerySuggestedCountryRes.country', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reward_gold', full_name='SanProto.QuerySuggestedCountryRes.reward_gold', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=446,
  serialized_end=526,
)


_UPDATECOUNTRYREQ = _descriptor.Descriptor(
  name='UpdateCountryReq',
  full_name='SanProto.UpdateCountryReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='old_country', full_name='SanProto.UpdateCountryReq.old_country', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='new_country', full_name='SanProto.UpdateCountryReq.new_country', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item_basic_id', full_name='SanProto.UpdateCountryReq.item_basic_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item_num', full_name='SanProto.UpdateCountryReq.item_num', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reward_gold', full_name='SanProto.UpdateCountryReq.reward_gold', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=528,
  serialized_end=650,
)


_UPDATECOUNTRYRES = _descriptor.Descriptor(
  name='UpdateCountryRes',
  full_name='SanProto.UpdateCountryRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='SanProto.UpdateCountryRes.status', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resource', full_name='SanProto.UpdateCountryRes.resource', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=652,
  serialized_end=728,
)

_UPDATEMONARCHREQ.fields_by_name['monarch'].message_type = _MONARCHINFO
_UPDATECOUNTRYRES.fields_by_name['resource'].message_type = resource_pb2._RESOURCEINFO
DESCRIPTOR.message_types_by_name['MonarchInfo'] = _MONARCHINFO
DESCRIPTOR.message_types_by_name['UpdateMonarchReq'] = _UPDATEMONARCHREQ
DESCRIPTOR.message_types_by_name['UpdateMonarchRes'] = _UPDATEMONARCHRES
DESCRIPTOR.message_types_by_name['QuerySuggestedCountryReq'] = _QUERYSUGGESTEDCOUNTRYREQ
DESCRIPTOR.message_types_by_name['QuerySuggestedCountryRes'] = _QUERYSUGGESTEDCOUNTRYRES
DESCRIPTOR.message_types_by_name['UpdateCountryReq'] = _UPDATECOUNTRYREQ
DESCRIPTOR.message_types_by_name['UpdateCountryRes'] = _UPDATECOUNTRYRES

MonarchInfo = _reflection.GeneratedProtocolMessageType('MonarchInfo', (_message.Message,), dict(
  DESCRIPTOR = _MONARCHINFO,
  __module__ = 'monarch_pb2'
  # @@protoc_insertion_point(class_scope:SanProto.MonarchInfo)
  ))
_sym_db.RegisterMessage(MonarchInfo)

UpdateMonarchReq = _reflection.GeneratedProtocolMessageType('UpdateMonarchReq', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEMONARCHREQ,
  __module__ = 'monarch_pb2'
  # @@protoc_insertion_point(class_scope:SanProto.UpdateMonarchReq)
  ))
_sym_db.RegisterMessage(UpdateMonarchReq)

UpdateMonarchRes = _reflection.GeneratedProtocolMessageType('UpdateMonarchRes', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEMONARCHRES,
  __module__ = 'monarch_pb2'
  # @@protoc_insertion_point(class_scope:SanProto.UpdateMonarchRes)
  ))
_sym_db.RegisterMessage(UpdateMonarchRes)

QuerySuggestedCountryReq = _reflection.GeneratedProtocolMessageType('QuerySuggestedCountryReq', (_message.Message,), dict(
  DESCRIPTOR = _QUERYSUGGESTEDCOUNTRYREQ,
  __module__ = 'monarch_pb2'
  # @@protoc_insertion_point(class_scope:SanProto.QuerySuggestedCountryReq)
  ))
_sym_db.RegisterMessage(QuerySuggestedCountryReq)

QuerySuggestedCountryRes = _reflection.GeneratedProtocolMessageType('QuerySuggestedCountryRes', (_message.Message,), dict(
  DESCRIPTOR = _QUERYSUGGESTEDCOUNTRYRES,
  __module__ = 'monarch_pb2'
  # @@protoc_insertion_point(class_scope:SanProto.QuerySuggestedCountryRes)
  ))
_sym_db.RegisterMessage(QuerySuggestedCountryRes)

UpdateCountryReq = _reflection.GeneratedProtocolMessageType('UpdateCountryReq', (_message.Message,), dict(
  DESCRIPTOR = _UPDATECOUNTRYREQ,
  __module__ = 'monarch_pb2'
  # @@protoc_insertion_point(class_scope:SanProto.UpdateCountryReq)
  ))
_sym_db.RegisterMessage(UpdateCountryReq)

UpdateCountryRes = _reflection.GeneratedProtocolMessageType('UpdateCountryRes', (_message.Message,), dict(
  DESCRIPTOR = _UPDATECOUNTRYRES,
  __module__ = 'monarch_pb2'
  # @@protoc_insertion_point(class_scope:SanProto.UpdateCountryRes)
  ))
_sym_db.RegisterMessage(UpdateCountryRes)


# @@protoc_insertion_point(module_scope)
