# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: soldier.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='soldier.proto',
  package='SanProto',
  serialized_pb=_b('\n\rsoldier.proto\x12\x08SanProto\"P\n\x0bSoldierInfo\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x10\n\x08\x62\x61sic_id\x18\x02 \x01(\x05\x12\r\n\x05level\x18\x03 \x01(\x05\x12\x14\n\x0cis_activated\x18\x04 \x01(\x08')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SOLDIERINFO = _descriptor.Descriptor(
  name='SoldierInfo',
  full_name='SanProto.SoldierInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='SanProto.SoldierInfo.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='basic_id', full_name='SanProto.SoldierInfo.basic_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='SanProto.SoldierInfo.level', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_activated', full_name='SanProto.SoldierInfo.is_activated', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=107,
)

DESCRIPTOR.message_types_by_name['SoldierInfo'] = _SOLDIERINFO

SoldierInfo = _reflection.GeneratedProtocolMessageType('SoldierInfo', (_message.Message,), dict(
  DESCRIPTOR = _SOLDIERINFO,
  __module__ = 'soldier_pb2'
  # @@protoc_insertion_point(class_scope:SanProto.SoldierInfo)
  ))
_sym_db.RegisterMessage(SoldierInfo)


# @@protoc_insertion_point(module_scope)
